version: '3.3'

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: testDb
      # So you don't have to use root, but you can if you like
      MYSQL_USER: testName
      # You can use whatever password you like
      MYSQL_PASSWORD: testPass
      # Password for root access
      MYSQL_ROOT_PASSWORD: password
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    networks:
      - mysqldb
    restart: unless-stopped
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysqldb:/var/lib/mysql
  pgadmin:
    links:
      - mysqldb:mysqldb
    image: fenglc/pgadmin4
    ports:
      - "5050:5050"
    networks:
      - mysqldb
    restart: unless-stopped
# Network bridging
networks:
  mysqldb:
    driver: bridge
# Names our volume
volumes:
  mysqldb: